package com.model;

/**
 * TOrderItem generated by MyEclipse Persistence Tools
 */

public class TOrderitem implements java.io.Serializable
{

	private String id;
	private String orderId;
	private Integer hangbanId;
	private String piaoleixing;//成人票，儿童票
	
	private Integer danjia;
	private Integer shuliang;
	
	private THangban hangban;//表里没有。自己加的

	public THangban getHangban()
	{
		return hangban;
	}

	public void setHangban(THangban hangban)
	{
		this.hangban = hangban;
	}

	public Integer getHangbanId()
	{
		return hangbanId;
	}

	public void setHangbanId(Integer hangbanId)
	{
		this.hangbanId = hangbanId;
	}

	public String getOrderId()
	{
		return orderId;
	}

	public void setOrderId(String orderId)
	{
		this.orderId = orderId;
	}


	public int getDanjia()
	{
		return danjia;
	}

	public void setDanjia(int danjia)
	{
		this.danjia = danjia;
	}


	public String getId()
	{
		return id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getPiaoleixing()
	{
		return piaoleixing;
	}

	public void setPiaoleixing(String piaoleixing)
	{
		this.piaoleixing = piaoleixing;
	}

	public Integer getShuliang()
	{
		return shuliang;
	}

	public void setShuliang(Integer shuliang)
	{
		this.shuliang = shuliang;
	}

	
}